### ISSUE TITLE
How to hacking

### ISSUE THREAD

**Issue by abdelnour09** [g3th/Netflix-Checker#10]

**Comment by abdelnour09** [comment]
How ?

**Comment by El7ANAFY-1337** [comment]
Hack What Web Apps OSs games ?

**Comment by g3th** [comment]
Please stop spamming with unrelated issues. "How to hack" is too general a question, where the umbrella term "hacking" touches an incredibly large number of domains. I suggest you buy some books.

I will close this non-issue.
